# Generated by Django 4.1.1 on 2022-09-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('character_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_1', to='graf_quests.character', verbose_name='Первый персонаж')),
                ('character_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character_2', to='graf_quests.character', verbose_name='Второй персонаж')),
            ],
        ),
    ]
