# Generated by Django 4.1.1 on 2022-09-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0002_alter_character_options_alter_character_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Роль'),
        ),
    ]
