# Generated by Django 4.1.1 on 2022-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0003_alter_link_options_character_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя'),
        ),
    ]
