# Generated by Django 4.1.1 on 2022-09-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0008_alter_questpoint_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Квест', 'verbose_name_plural': 'Квесты'},
        ),
        migrations.AlterModelOptions(
            name='questpoint',
            options={'verbose_name': 'Часть квеста', 'verbose_name_plural': 'Части квестов'},
        ),
        migrations.RenameField(
            model_name='questpoint',
            old_name='quest_id',
            new_name='quest',
        ),
    ]
