# Generated by Django 4.1.1 on 2022-09-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0009_alter_quest_options_alter_questpoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
