# Generated by Django 4.1.1 on 2022-09-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0010_questpoint_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questpoint',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
