# Generated by Django 4.1.1 on 2022-09-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0012_alter_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Игрушка',
                'verbose_name_plural': 'Игрушки',
            },
        ),
    ]
