# Generated by Django 4.1.1 on 2022-09-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0015_link_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='graf_quests.game'),
            preserve_default=False,
        ),
    ]
