# Generated by Django 4.1 on 2022-10-10 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0017_alter_character_game_alter_link_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questpoint',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graf_quests.character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graf_quests.quest', verbose_name='Квест'),
        ),
    ]
