# Generated by Django 4.0 on 2023-05-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0018_alter_questpoint_character_alter_questpoint_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Общедоступная'),
        ),
        migrations.AlterField(
            model_name='link',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='step',
            field=models.FloatField(verbose_name='Шаг'),
        ),
    ]
