# Generated by Django 4.0 on 2023-05-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0019_game_is_open_alter_link_text_alter_questpoint_step'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_open',
            new_name='is_nav',
        ),
    ]
