# Generated by Django 4.0 on 2023-05-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('graf_quests', '0020_rename_is_open_game_is_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='Навигационная панель'),
        ),
    ]
