# Generated by Django 4.0 on 2023-05-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('graf_quests', '0021_game_responsible_alter_game_is_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chat',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Чат'),
        ),
        migrations.AddField(
            model_name='game',
            name='discussion',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Обсуждение'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новая'),
        ),
        migrations.AlterField(
            model_name='game',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Ответственный'),
        ),
    ]
