# Generated by Django 4.0 on 2023-05-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0022_game_chat_game_discussion_game_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='chat',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='game',
            name='discussion',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Обсуждение'),
        ),
    ]
