# Generated by Django 4.0 on 2023-05-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0023_alter_game_chat_alter_game_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='doc',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Док'),
        ),
    ]
