# Generated by Django 4.0 on 2023-05-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0024_game_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ReadyGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='ready',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graf_quests.readygame'),
        ),
    ]
