# Generated by Django 4.0 on 2023-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0025_readyclub_readygame_game_ready'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readyclub',
            options={'verbose_name': ('Готовность клуба',), 'verbose_name_plural': 'Готовности клубов'},
        ),
        migrations.AlterModelOptions(
            name='readygame',
            options={'verbose_name': 'Готовность игрушки', 'verbose_name_plural': 'Готовности игрушек'},
        ),
        migrations.AddField(
            model_name='readyclub',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readygame',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
