# Generated by Django 4.0 on 2023-06-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0026_alter_readyclub_options_alter_readygame_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readyclub',
            options={'ordering': ['percent'], 'verbose_name': ('Готовность клуба',), 'verbose_name_plural': 'Готовности клубов'},
        ),
        migrations.AlterModelOptions(
            name='readygame',
            options={'ordering': ['percent'], 'verbose_name': 'Готовность игрушки', 'verbose_name_plural': 'Готовности игрушек'},
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
