# Generated by Django 4.0 on 2023-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0027_alter_readyclub_options_alter_readygame_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questpoint',
            name='stuff',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Стафф'),
        ),
        migrations.AddField(
            model_name='questpoint',
            name='todo',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Что доделать'),
        ),
    ]
