# Generated by Django 4.0 on 2023-07-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0028_questpoint_stuff_questpoint_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['game', 'role', 'name'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='character',
            name='stuff',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Стафф'),
        ),
        migrations.AddField(
            model_name='character',
            name='todo',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Что доделать'),
        ),
        migrations.AlterField(
            model_name='questpoint',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graf_quests.character', verbose_name='Персонаж'),
        ),
    ]
