# Generated by Django 4.1.4 on 2023-07-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0030_character_prep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='prep',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сотрудник'),
        ),
    ]
