# Generated by Django 4.1.4 on 2024-07-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0032_alter_character_game_alter_link_character_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('fire_data', models.JSONField()),
                ('rainbow_data', models.JSONField()),
                ('fill_data', models.JSONField(blank=True, default='', null=True)),
            ],
        ),
    ]
