# Generated by Django 4.0 on 2024-10-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0033_strip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Strip',
        ),
    ]
