# Generated by Django 4.0 on 2024-10-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0036_remove_game_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chat_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id сообщения'),
        ),
    ]
