# Generated by Django 4.0 on 2023-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setka', '0002_rename_clubs_club_alter_club_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='doc',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Док'),
        ),
    ]
