# Generated by Django 4.0 on 2023-05-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0024_game_doc'),
        ('setka', '0005_day_club_day_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day', to='setka.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='day',
            name='game',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day', to='graf_quests.game', verbose_name='Игрушка'),
        ),
    ]
