# Generated by Django 4.0 on 2023-05-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graf_quests', '0025_readyclub_readygame_game_ready'),
        ('setka', '0006_alter_day_club_alter_day_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='ready',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='graf_quests.readyclub'),
        ),
    ]
