# Generated by Django 4.1.4 on 2023-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setka', '0011_alter_tasktime_options_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='Файл', max_length=256),
        ),
    ]
