# Generated by Django 4.1.4 on 2024-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setka', '0012_alter_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(default='Название файла', max_length=256, verbose_name='Название файла'),
        ),
    ]
