# Generated by Django 4.0 on 2024-10-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_prep_options'),
        ('setka', '0013_alter_file_file_alter_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.prep', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='dotask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.prep'),
        ),
        migrations.AlterField(
            model_name='task',
            name='otv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.prep'),
        ),
    ]
