# Generated by Django 4.0 on 2024-10-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setka', '0014_alter_club_responsible_alter_dotask_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='discussion',
        ),
    ]
