# Generated by Django 4.0 on 2024-10-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setka', '0015_remove_club_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='chat_message_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id сообщения'),
        ),
    ]
