# Generated by Django 4.0 on 2024-10-25 15:20

from django.db import migrations, models
import django.db.models.deletion
import free_time.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_prep_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('weekday', models.IntegerField(blank=True, null=True, verbose_name='День недели')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('slug', models.SlugField(default=free_time.models.get_token_slug, editable=False, max_length=255, unique=True, verbose_name='URL')),
                ('prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.prep')),
            ],
            options={
                'verbose_name': 'Свободное время',
                'verbose_name_plural': 'Свободные времена',
            },
        ),
    ]
