# Generated by Django 4.0 on 2024-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0002_alter_freetime_prep'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dates', models.TextField(verbose_name='Даты')),
            ],
        ),
        migrations.CreateModel(
            name='FreeTimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(max_length=6, verbose_name='Цвет')),
                ('weight', models.IntegerField(verbose_name='Вес')),
            ],
        ),
    ]
