# Generated by Django 4.0 on 2024-10-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0004_rename_freetimestatus_freetimetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetimetype',
            name='color',
            field=models.CharField(max_length=256, verbose_name='Цвет'),
        ),
    ]
