# Generated by Django 4.0 on 2024-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0005_alter_freetimetype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetime',
            name='date',
        ),
        migrations.RemoveField(
            model_name='freetime',
            name='weekday',
        ),
        migrations.AddField(
            model_name='freetime',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
