# Generated by Django 4.0 on 2024-10-28 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0008_freetime_event_freetimeevent_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetime',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='free_time.freetimeevent'),
        ),
    ]
