# Generated by Django 4.0 on 2024-10-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0013_alter_freetime_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetimeevent',
            name='default_free_time_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='free_time.freetimetype'),
        ),
    ]
