# Generated by Django 4.0 on 2024-10-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0014_freetimeevent_default_free_time_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetime',
            name='name',
            field=models.CharField(blank=True, default='Иванов Иван Иванович', max_length=256, null=True, verbose_name='Подпись'),
        ),
    ]
