# Generated by Django 4.0 on 2024-10-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0017_remove_freetimeevent_default_free_time_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetimeevent',
            name='weekdays',
        ),
        migrations.AddField(
            model_name='freetimeevent',
            name='default_free_time_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='free_time.freetimetype'),
        ),
    ]
