# Generated by Django 4.0 on 2024-10-31 21:55

from django.db import migrations, models
import free_time.models


class Migration(migrations.Migration):

    dependencies = [
        ('free_time', '0019_freetimetype_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetimeevent',
            name='slug',
            field=models.CharField(default=free_time.models.get_token_slug, max_length=255),
        ),
    ]
