# Generated by Django 4.0 on 2024-10-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_prep_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prep',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
