# Generated by Django 4.0 on 2024-10-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_prep_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prep',
            name='free_time_modal',
            field=models.BooleanField(default=True, verbose_name='Показывать модальное окно с подсказками при выборе свободного времени'),
        ),
    ]
